version: "3.9"

services:
  app:
    container_name: weather-api-app
    build: .
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - weather-api-network

  redis:
    container_name: weather-api-redis
    image: redis/redis-stack
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redisdata:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - weather-api-network

networks:
  weather-api-network:
    name: weather-api-network
    driver: bridge