version: "3.9"

services:
  app:
    container_name: weather-api-app
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - weather-api-network
    restart: on-failure

  redis:
    container_name: weather-api-redis
    image: redis/redis-stack
    ports:
      - 6380:6379
    volumes:
      - ./redisdata:/data
    networks:
      - weather-api-network
    restart: on-failure

networks:
  weather-api-network:
    name: weather-api-network
    driver: bridge

volumes:
  redis_data: